version: "3.9"

services:
  api:
    build:
      context: "TitanMarketBackend/TitanMarket.WebApi"
    image: "localhost:7002/titanmarket-api:${IMAGE_TAG}"
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"
  web:
    build:
      context: "TitanMarketFrontend"
    image: "localhost:7002/titanmarket-web:${IMAGE_TAG}"
    container_name: "${WEB_CONT_NAME}"
    ports:
      - "${WEB_PORT}:80"
    
