version: "3.9"

services:
  api:
    build:
      context: "TitanMarketBackend/TitanMarket.WebApi"
    image: "185.51.76.36:7002/titanmarket-api:${IMAGE_TAG}"
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"   
    
