version: "3.9"

services:
  api:
    build:
      context: "TitanMarketBackend/TitanMarket.WebApi"
    image: "185.51.76.36:7002/titanmarket-api:${IMAGE_TAG}"
    container_name: "${API_CONT_NAME}"
    ports:
      - "${API_PORT}:80"
  docker-registry:
    image: "registry"
    volumes:
      - "registry_data:/var/lib/registry"
    ports:
      - "7002:5000"
  docker-registry-ui:
    image: "parabuzzle/craneoperator"
    ports:
      - "7003:80"    
    
